spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: chien
      password: password123
      database: reviewcongty
  resources:
    static-locations:
      - file:/home/chiennm/public/
      - classpath:/static/
      - classpath:/public/
