spring:
  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  # Static resources reloading during development
  resources:
    static-locations: file:src/main/resources/static/
    cache:
      period: 0

  data:
    mongodb:
      host: localhost
      port: 27017
      database: reviewcongty
#  mvc:
#    locale-resolver: fixed

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    com.reviewcongty.backend: DEBUG

google:
  recaptcha:
    site-key: 6LdxtvkUAAAAAPXKazewNm-_MmkNpCyt8Y7liizk
    secret-key: 6LdxtvkUAAAAAEtgEU3kz4pIzc9P5-YmLDQ4h3gi

