spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: chien
      password: password123
      database: reviewcongty
  resources:
    static-locations:
      - file:/home/chiennm/public/
      - classpath:/static/
      - classpath:/public/

google:
  recaptcha:
    site-key: 6LfXFgEVAAAAAGytifrzgioMdnu30K3Vbo-0pjaM
    secret-key: 6LfXFgEVAAAAABY9wKMIa9GbJyGbXbOQGC8Vq8Yp