spring:
  data:
    mongodb:
      host: 139.180.145.60
      port: 27017
      username: chien
      password: password123
      database: reviewcongty
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
