spring:
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy

  mvc:
    static-path-pattern: /content/**

  messages:
    basename: i18n/messages

google:
  recaptcha:
    site-key:
    secret-key: